force-app/main/default/objects/SLA_History__c/SLA_History__c.object-meta.xml
<CustomObject>
    <label>SLA History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>SLA History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLA_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SLA History</relationshipLabel>
    <relationshipName>SLA_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLA_History__c/fields/Changed_On__c.field-meta.xml
<CustomField>
    <fullName>Changed_On__c</fullName>
    <label>Changed On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SLA_History__c/fields/New_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Status__c</fullName>
    <label>New Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Near Breach</fullName>
            </value>
            <value>
                <fullName>Breached</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_History__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <label>Old Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Near Breach</fullName>
            </value>
            <value>
                <fullName>Breached</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Tracker__c/SLA_Tracker__c.object-meta.xml
<CustomObject>
    <label>SLA Tracker</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>SLA Tracker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLA_Tracker__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SLA Trackers</relationshipLabel>
    <relationshipName>SLA_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLA_Tracker__c/fields/SLA_DeadLine__c.field-meta.xml
<CustomField>
    <fullName>SLA_DeadLine__c</fullName>
    <formula>IF(ISPICKVAL(Case__r.Priority , &quot;High&quot;)  , (SLA_Start_Time__c + (8/24)),
  IF( ISPICKVAL(Case__r.Priority, &quot;Medium&quot;) ,(SLA_Start_Time__c + 1), (SLA_Start_Time__c + 2)) )</formula>
    <label>SLA DeadLine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLA_Tracker__c/fields/SLA_Status__c.field-meta.xml
<CustomField>
    <fullName>SLA_Status__c</fullName>
    <label>SLA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Breached</fullName>
            </value>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Near Breach</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SLAStatusScheduler.cls
global class SLAStatusScheduler implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        
        // 1️⃣ Get Escalation Queue Id
        Id escalationQueueId = [
            SELECT Id
            FROM Group
            WHERE Type = 'Queue'
            AND Name = 'SLA_Escalation_Queue'
            LIMIT 1
        ].Id;
        
        List<SLA_Tracker__c> trackersToUpdate = new List<SLA_Tracker__c>();
        List<Case> casesToUpdate = new List<Case>();
        List<SLA_History__c> historyList = new List<SLA_History__c>();
        
        
        List<SLA_Tracker__c> trackers = [
            SELECT Id,
                   SLA_Deadline__c,
                   SLA_Status__c,
                   Case__c,
                   Case__r.OwnerId,
                   Case__r.Priority
            FROM SLA_Tracker__c
            WHERE SLA_Deadline__c != null AND SLA_Status__c != 'Breached' AND SLA_Status__c != 'Met'
        ];
        
        Datetime nowTime = System.now();
        
        for (SLA_Tracker__c tracker : trackers) {
            
            Long remainingMinutes =
                (tracker.SLA_Deadline__c.getTime() - nowTime.getTime()) / (1000 * 60);
            
            String newStatus;
            
            if (remainingMinutes <= 0) {
                newStatus = 'Breached';
            } else if (remainingMinutes <= 120) {
                newStatus = 'Near Breach';
            } else {
                newStatus = 'Active';
            }
            
            // Update SLA Tracker if status changed
            if (tracker.SLA_Status__c != newStatus) {
                tracker.SLA_Status__c = newStatus;
                trackersToUpdate.add(tracker);
                
                // 🔥 ESCALATION LOGIC
                if (newStatus == 'Breached' && tracker.Case__c != null) {
                    Case c = new Case(
                        Id = tracker.Case__c,
                    OwnerId = escalationQueueId,
                    Priority = 'High'
                        );
                    casesToUpdate.add(c);
                }
                
                //Create SLA History Record
                SLA_History__c history = new SLA_History__c(
                    Case__c = tracker.Case__c,
                Old_Status__c = tracker.SLA_Status__c,
                New_Status__c = newStatus,
                Changed_On__c = System.today()
                    );
                historyList.add(history);
                
            }
        }
        
        if (!trackersToUpdate.isEmpty()) {
            update trackersToUpdate;
        }
        
        if (!historyList.isEmpty()) {
            insert historyList;
        }
        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
    }
}